production:
  adapter: mysql2
  database: anstak_tz
  host: localhost
  username: anstak_tz
  password: 001137001137
  encoding: utf8

development:
  adapter: mysql2
  database: anstak_tz
  host: localhost
  username: anstak_tz
  password: 001137001137
  encoding: utf8